version: '3.1'
services:
    centrifugo:
        container_name: centrifugo
        image: centrifugo/centrifugo
        restart: always
        command: centrifugo --engine=redis --redis_host=redis --redis_port=6379
        ports:
            - 8000:8000
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        volumes:
        - ./.centrifugo-data:/centrifugo
    redis: 
        container_name: redis
        image: redis
        ports:
            - 6379:6379
        volumes:
        - ./.redis-data:/var/lib/redis